#!/bin/sh
#
# Commit message verification git hook
# - Check the message has correct prefix and signed-off
#
# Author: aKuad
#

msg_firstline=`cat "$1" | grep -v '^#' | grep -v '^\s*$' | sed -n -e '1p'`
#                         ~~~~~~~~~~~~   ~~~~~~~~~~~~~~~
#                       Ignore comment   Ignore blank or spaces only lines

is_verify_ok=1

if [ "`echo "$msg_firstline" | grep -E '^(Add|Mod|Fix): \S'`" = "" ]; then
  echo "\033[1;31mInvalid prefix\033[0m" > /dev/stderr
  echo "\033[0;33m    Hint: Prefix must be 'Add:', 'Mod:' or 'Fix:'\033[0m" > /dev/stderr
  echo "\033[0;33m          And only 1 whitespace must be had between prefix and message body\033[0m" > /dev/stderr
  is_verify_ok=0
fi

if [ "`cat $1 | grep '^Signed-off-by:'`" = "" ]; then
  echo "\033[1;31mNo signed-off\033[0m" > /dev/stderr
  echo "\033[0;33m    Hint: -s option to sign-off\033[0m" > /dev/stderr
  is_verify_ok=0
fi

if [ $is_verify_ok = 0 ]; then
  exit 1  # disallow commiting
fi

exit 0
